env:
    OEM: oneplus
    CODENAME: avicii
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: pbrp
    CR_NAME: pitchblack
    USERNAME: imranpopz
    USERMAIL: imranpopz32@gmail.com
    CR_REPO: https://github.com/PitchBlackRecoveryProject/manifest_pb.git
    CR_BRANCH: android-12.1
    DT_REPO: https://github.com/Sanju0910/pitchblack_device_oneplus_avicii.git
    DT_BRANCH: android-12.1
    CIRRUS_CHANGE_TITLE: Building PithBlack Recovery for ${COMENAME} from ${OEM}
    CIRRUS_CHANGE_MESSAGE: Building PithBlack Recovery for ${COMENAME} from ${OEM}
    
task:
  name: "Recovery Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/sanju0910/ubuntu:latest
      cpu: 8
      memory: 32G

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/sync.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/build.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/Sanju0910/Cirrus_CI/main/scripts/upload.sh | bash
