name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  TARGET: "pbrp"

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:
       - name: Auto Adapt Manifest
         # /* if your branch name is other than the one which you dispatched workflow from then set it manually in the place of ${GITHUB_REF##*/}" */ 
         run: echo "MANIFEST=https://github.com/PitchBlackRecoveryProject/manifest_pb -b ${GITHUB_REF##*/}" >> $GITHUB_ENV

       - uses: actions/checkout@v1
       - name: Run a one-line script
         run: sed -i 's/oneplus/xiaomi/g' ./.cirrus.yml
         
       - name: check for changes
         run: git status
