name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'

      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
       

      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true

      DEVICE_TREE_BRANCH:

        description: 'DEVICE_TREE_BRANCH'

        required: true

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:

       - uses: actions/checkout@v1
       - name: Run a one-line script
         run: |
              sed '11 c\    CR_BRANCH:${{ github.event.inputs.MANIFEST_BRANCH }}' ./.cirrus.yml
       
       
              sed '12 c\    DT_REPO:${{ github.event.inputs.DEVICE_TREE_URL }}' ./.cirrus.yml 
        

              sed '13 c\    DT_BRANCH:${{ github.event.inputs.DEVICE_TREE_BRANCH }}' ./.cirrus.yml 
        
       
              sed '3 c\    CODENAME:sweet' ./.cirrus.yml 
        
       - name: Git config
         run: |
              git status
              git config --global user.email "imranpopz32@gmail.com"

              git config --global user.name "imranpopz"
       - name: Diff changed files
         run: git diff

       - name: Diff changed files

         run: git add *
         
       - name: Diff changed files
         run: git commit -m "test"
         
       - name: Diff changed files
         run: git push
