name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'

      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-12.1'

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:

       - uses: actions/checkout@v1
       - name: Run a one-line script
         run: sed '11 c\    CR_BRANCH:${{ github.event.inputs.MANIFEST_BRANCH }}';'3 c\        CODENAME:sweet' ./.cirrus.yml 
        
       - name: check for changes
         run: git status

       - name: Diff changed files
         run: git diff
