name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:

      
        
jobs:
  PBRP_CI:
    runs-on: ubuntu-latest
    container:

      image: jetbrains/teamcity-server

    steps:


       - name: Run a one-line script
         run: |
              df -h
              

           
