name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:

      VENDOR_NAME:
        description: 'VENDOR_NAME'
        required: true

      DEVICE_CODENAME:
        description: 'DEVICE_CODENAME'
        required: true
                
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
       
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true

      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true

      COMMIT_MSG:
        description: 'COMMIT_MSG'
        required: true
        
jobs:
  PBRP_CI:
    runs-on: jetbrains/teamcity-server

    steps:

       - uses: actions/checkout@master
         with:

          persist-credentials:  false     
       
       - name: Run a one-line script
         run: |
              df -h
              

           
