name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:

      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
       
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true

      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:

       - uses: actions/checkout@master
         with:

          persist-credentials:  false     
       
       - name: Run a one-line script
         run: |
              sed -i '11 c\    CR_BRANCH:${{ github.event.inputs.MANIFEST_BRANCH }}' ./.cirrus.yml
              sed -i '12 c\    DT_REPO:${{ github.event.inputs.DEVICE_TREE_URL }}' ./.cirrus.yml 
              sed -i '13 c\    DT_BRANCH:${{ github.event.inputs.DEVICE_TREE_BRANCH }}' ./.cirrus.yml 
              sed -i '3 c\    CODENAME:sweet' ./.cirrus.yml 
        
        

       - name: Commit & Push changes
         uses: actions-js/push@master
         
