name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:

      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
       
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true

      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:

       - uses: actions/checkout@v1
       - name: Run a one-line script
         run: |
              sed -i '11 c\    CR_BRANCH:${{ github.event.inputs.MANIFEST_BRANCH }}' ./.cirrus.yml
              sed -i '12 c\    DT_REPO:${{ github.event.inputs.DEVICE_TREE_URL }}' ./.cirrus.yml 
              sed -i '13 c\    DT_BRANCH:${{ github.event.inputs.DEVICE_TREE_BRANCH }}' ./.cirrus.yml 
              sed -i '3 c\    CODENAME:sweet' ./.cirrus.yml 
        
       - name: Push changes
         run: |
              git status
              git config --global user.email "imranpopz32@gmail.com"
              git config --global user.name "imranpopz"
              git diff
              git add *
              git commit -m "test"
              git push origin HEAD:android-12.1
