name: PBRP Organization CI
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/BETA/OFFICIAL)'
        required: true
        default: 'TEST'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Sync Latest Source'

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  TARGET: "pbrp"

jobs:
  PBRP_CI:
    runs-on: ubuntu-20.04

    steps:
       - name: Auto Adapt Manifest
         # /* if your branch name is other than the one which you dispatched workflow from then set it manually in the place of ${GITHUB_REF##*/}" */ 
         run: echo "MANIFEST=https://github.com/PitchBlackRecoveryProject/manifest_pb -b ${GITHUB_REF##*/}" >> $GITHUB_ENV

       - name: Export Vars
         run: |
              if [[ ${BUILD_RELEASE_TYPE} == "TEST" ]]; then echo "TEST_BUILD=true"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "BETA" ]]; then echo "BETA_BUILD=true"  >> $GITHUB_ENV;fi
              if [[ ${BUILD_RELEASE_TYPE} == "OFFICIAL" ]]; then echo "PB_OFFICIAL=true"  >> $GITHUB_ENV;fi

       - name: Recovery Compilation
         uses: actions/checkout@v2
         with:
           repository: PitchBlackRecoveryProject/Compiler
           ref: production
           token: ${{ secrets.GH_BOT_TOKEN }}
           uses: ./.github/actions/Compiler
